nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:8000']
        allow_credentials: false
        allow_headers: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        expose_headers: []
        max_age: 0

    paths:
        '^/': null
